### ISSUE TITLE
Django admin/third party assets using webpack

### ISSUE THREAD

**Issue by asifpy** [owais/django-webpack-loader#144] opened 2018-02-08 08:54 UTC
As I'm new to the webpack world, it will be great to know how to bundle django admin JS/CSS with my default bundle.

The goal is to understand how to accommodate any third party assets using this package. Currently I'm working on project which heavily relies on `django-select2` and other django packages'. In this case how i can tell the webpack to bundle all the assets related to `django-select2` which will get used both during development and production.

**Comment by jpic** [comment] 2018-03-12 10:17
Dupe of #141?
Except you add the admin but forget the admin there's nothing elegant that we're going to be able to do given the current situation.

**Comment by owais** [comment] 2018-04-03 11:06
django-select2 should have it's own mechanism to deliver assets to the browser as it would integrate with django's staticfiles management system.This sound orthogonal to what django-webpack-loader does. You probably might not even need django-webpack-loader. Thiis package is usually helpful for building SPAs that are delivered by a Django backend. If you need to use select2  in your SPA then you'd install it through npm/yarn and use directly. You wouldn't need django-select2 in that case.

**Closed by owais** 2018-04-03 11:06 UTC
